#!/bin/tcsh -f

# Need to have access to the Jython netlister program

set netlister_dir = ~/Documents/nas/Development/git/netlister
which netlister.py > /dev/null
if ($status != 0) then
   setenv CLASSPATH ${netlister_dir}/src:$CLASSPATH
   setenv PATH      ${netlister_dir}/src:$PATH
   rehash
endif

setenv TERM xterm


cp ./autorouter_74.ctl /tmp
cp ./design_rules.dru /tmp

## Revised CPLD based RAM board - 464 and 6128
make cpc_cpucard.net
make cpc_cpucard.scr
